import CouchDBStorage from './CouchDBStorage'
import { arrSort, generateHash, isFn, isStr, isValidNumber } from './utils/utils'
import { setTexts } from './language'

const currencies = new CouchDBStorage(null, 'currencies')
let tickersHash = '' // hash of sorted array of supported currency tickers
const messages = setTexts({
    invalidRequest: 'Missing one or more of the required fields',
    notFound: 'Unsupported currency'
})

const getAll = async (ids = null, asMap = true, limit = 9999) => await currencies.getAll(ids, asMap, limit)

// convert currency using exchange rates stored in the database
//
// Params:
// @from        string: source currency ticker (ISO string). Eg: USD
// @to          string: target currency ticker (ISO string). Eg: EUR
// @amount      number: the amount to convert to @to currency
// @callback    function: args => 
//                  @err                string: error message if request failed. Otherwise, null.
//                  @convertedAmount    number: converted amount
export const handleCurrencyConvert = async (from, to, amount, callback) => {
    if (!isFn(callback)) return
    if (!isStr(from) || !from || !isStr(to) || !to || !amount || !isValidNumber(amount))
        return callback(messages.invalidRequest)

    const fromCurrency = await currencies.find({
        ISO: from.toUpperCase(),
    }, true, true, false)
    if (!fromCurrency) return callback(`${messages.notFound}: ${from}`)

    const toCurrency = await currencies.find({
        ISO: to.toUpperCase(),
    }, true, true, false)
    if (!toCurrency) return callback(`${messages.notFound}: ${to}`)

    const convertedAmount = (fromCurrency.ratioOfExchange / toCurrency.ratioOfExchange) * amount
    callback(null, convertedAmount)
}

// retrive an array of supported currencies
//
// Params:
// @hash        string: a hash generated by the client's cached array (sorted by field: ISO) of currencies
// @callback    function: args => 
//                  @err            string: error message if request failed. Otherwise, null.
//                  @currencies     array: list of currencies, unsorted
export const handleCurrencyList = async (hash, callback) => {
    if (!isFn(callback)) return
    // whether or not client needs to update the list of tickers
    const shouldUpdate = hash !== tickersHash
    callback(null, !shouldUpdate ? [] : await getAll(null, false))
}

// initialize
setTimeout(async () => {
    // create an index for the field `currency`, ignores if already exists
    const indexDef = {
        index: { fields: ['ISO'] },
        name: 'ISO-index',
    }
    const tickers = arrSort(await getAll(null, false), 'ISO')
    tickersHash = generateHash(tickers)
    await (await currencies.getDB()).createIndex(indexDef)
})